language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- 3.8-dev
- nightly
install:
- pip install -r requirements.txt
- pip install .
env:
  global:
    - secure: "XsCvc9d4HLciAlftTT7zSutQKxAkpN04ou0ONvBDcdhBtsZpuOTFmd6S0i6gCPdfwKVY63pU0ymLtcIgzl4ob6ilNhg478ukFRasDINy903lkBa6sbkfMPm9kX4ZN7BQiTNLw20Wq3D/iZ7QFZATKM5MH6VJ0NDjGMc57oUdUB6Zr9lRa9LO6/zYeXUbR7m5/zwQpPWrXG0lsqJFEHfIFG4641iVLflutoJ3KIKlIs6BRNBZ/ZXagp57oLxmSmQiLe/uGMQaq6vjnn4DwYCk7x0LgPc45CuYEcod7EfL0wgzvVsggP4DrfklzUKRQH2HZ09bWkXEObre1gzMeNnDDJxi/f5LR/t8mIE0GNA5/CS598anQnXRs44SfIbW2jINYGu28t3ukGix+Ey4bm9S3ERnWSZqDYL1Gf89ws90RsSozUruwI2NflIZoLorgobvGWTGgwa+ATSBux2boQ/VT+E4U+hQSQwQDGnOJy38RA6NPxKiAFDihrPw2f7hwcfqH6j3koamcs7VKWOiiAQMxWGDP0C/iJz6JlQLNlq2tGlnj6binw2QQUBZGrau9lmCN3NqHZkbPU2PJMLhzm5O2vXVie2OX9/+tO3mMvDXOhYkwzq3D9+4l2TDvCzoqRqKT/whci8ihMgqzN5Z9GtWn/vZ7ZSxSWplj9t8Q65iXhI="
    - secure: "by2FB0Eu/HTKQLcgNJQzGvfXY0tHxA5QoxO0YvdYyF1zsqQ3M5+2kfSLoct+LfleBo1aemVAOpvC2fCeD7DSo7a/Ehl3FDrFuwfHBSjJSELTLbZF7DzyWcmqGV8o9VMXjIQObWUBUZlWCGKM/qnYJxEuw31B1D7L41bAShw5V3F9QRoxVnwSeLlvBFx2OmDTfdOSJgs4Tz2CUpEWlNXt8UkClylyDWaOJknLHZ4MH7cvzJWvhf7Lt8hGH0XpR+hR8fbXwzlnsXHWf/wL+oLtQtKkMgnVmKczZonDBPlArgk/21Ksj0WqxfLaBPwTvNuzara/vebuTS3VtQarrjPXvzQFl3LJPFUR/RFTh/28FPoEVI1CsuIHdYasv8CukBV6Mbl36kDYunz0eV4pcHSJ8OhtQnyIGVctHLJ1w/1RDX1566k9NYzl8SQAUOe2trYUnGNJ0F9HltbZTSp2oVU8HfT5z214cO34NRE6CioMfyXc1s2LXSSQ/YqQFWhYDy5O9Pdu46U1kFlHbIb76HJhrjJal9pH47XD1vls2Yv2LN7hXwWD+D6WhzlDDEaS/Tja3qSYrobPzN1IOHHB+s++a3TxWw0H5hy2WnRHZH8at2mjnwGLBM45NS0ygsm8QMfJ8E9q1D0D4eYexB5cl38vjCX26WGY2FBskwQlkNDhfV8="
script:
- export EMAIL=$EMAIL
- export PASSWORD=$PASSWORD
- pytest
